/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询可见方案 */
        get: operations["listPlans"];
        put?: never;
        /** 根据赛题和平台维度生成方案草稿 */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        /** 读取方案当前草稿或指定定稿修订 */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/plans/{plan_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 保存完整草稿，允许指标细则未完成
         * @description 无草稿时以最新定稿的 ETag 创建下一修订；有草稿时更新当前草稿。不会修改已有定稿。缺少指标内容形成 validation_issues，不当作保存失败。
         */
        put: operations["savePlanDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/plans/{plan_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 为尚无指标的维度补生成细则
         * @description 无请求体。需要当前草稿，仅补尚无指标的维度，不覆盖已编辑指标。无待生成维度时返回 409 PLAN_NOTHING_TO_GENERATE；正在生成同一输入时复用 Job。
         */
        post: operations["generateMissingPlanDimensions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/plans/{plan_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 冻结当前完整草稿
         * @description 无请求体。仅做当前草稿的完整性、归属、精确求和和修订检查，不调用模型或取证工具。返回 status=finalized、content_sha256 非空。
         */
        post: operations["finalizePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 异步解析评测配置候选，不创建 Run */
        post: operations["previewReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询可见评测 */
        get: operations["listReviews"];
        put?: never;
        /** 创建单条评测 */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按单条请求语义批量接纳 */
        post: operations["createReviewsBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/batch/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量只读同步状态
         * @description 无写副作用，不需要 Idempotency-Key。按租户批量读取，不逐项创建数据库请求。
         */
        post: operations["getReviewStatusesBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 读取执行和 AI 结果状态 */
        get: operations["getReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 保存自动评测取消意图
         * @description 无请求体。不撤回已保存评分或人工结果，不取消其他 Run。终态返回实际状态，不假称外部进程已停止。
         */
        post: operations["cancelReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 仅恢复指定缺失或失败部分 */
        post: operations["retryReviewPart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 读取 AI 分数和已保存评价 */
        get: operations["getScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/human-results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 读取当前人工结果与修订号 */
        get: operations["getHumanResults"];
        put?: never;
        /**
         * 原子保存完整人工结果
         * @description expected_revision=0 表示首次提交，后续等于当前人工修订；同幂等键重放先返回原回执，不误判版本冲突。只接收配置需要的人工维度，不接收权重或 AI 分。
         */
        post: operations["submitHumanResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 读取两路汇总及具体缺项 */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * 按类型读取报告发布状态和阅读数据
         * @description ai 和 summary 独立来源、权限、状态与发布指针。无报告或发布失败仍返回 200；body 中说明原因。
         */
        get: operations["getPublication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 分页读取已就绪截图、DOM、源码片段和操作证据 */
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        /**
         * 鉴权代理读取不可变产物正文
         * @description 先验证租户及所属 Run 和产物类型权限，再读取缓存/S3；证据需 evidence.read，AI/summary 报告分别需对应读取权限。路径中的 ID 不是访问凭据。range 首期不支持，不发放带服务 Token 的 URL。
         */
        get: operations["readArtifactContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** 按游标补读脱敏执行事件 */
        get: operations["listReviewEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reviews/{run_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** SSE 补读并跟随同一持久化序列 */
        get: operations["streamReviewEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        /**
         * 查询方案、预览或后台作业
         * @description 按所属方案/Run及 Job 类型授权。仅拥有人工作写权限的调用方可查其汇总更新回执状态，不能借 result 读取 AI/汇总正文。
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 不透明标识，按字符串往返，不能转 JS number */
        Identifier: string;
        /** @description 评分维度或指标的英文稳定键，小写字母开头，可含数字和下划线；维度键由平台提供，指标键由服务分配，各自按所属范围关联。 */
        ScoringKey: string;
        /** @description 0..1 四位比例，0.2000=20.00%；精确转整数万分位 */
        Ratio: string;
        /** @description 百分制分数，无百分号；计算时精确十进制解析，0 是有效分 */
        Score: number;
        NullableScore: components["schemas"]["Score"] | null;
        Revision: number;
        NullableRevision: components["schemas"]["Revision"] | null;
        /**
         * Format: date-time
         * @description 带时区 RFC3339，显示端可转北京时间
         */
        Timestamp: string;
        NullableTimestamp: components["schemas"]["Timestamp"] | null;
        Sha256: string;
        NullableId: components["schemas"]["Identifier"] | null;
        /**
         * Format: uri
         * @description 传输机密地址不原样入日志；域名、DNS、重定向、实际连接另行执行出网策略
         */
        HttpUrl: string;
        /** @description 同一 API 的相对路径，仍需鉴权，不含服务 Token */
        RelativeUrl: string;
        /** @description 可缺省或 null；保留用户原文及换行。拒绝不可见危险控制字符，不限制语言。 */
        Comment: string | null;
        /** @description 平台非敏感关联信息，不参与授权或计分 */
        Metadata: {
            [key: string]: string | number | boolean | null;
        };
        Challenge: {
            /** @description 赛题名称，由平台提供。 */
            title: string;
            /** @description 赛题要求和目标的原始文本，不是模型工具权限。 */
            requirements: string;
            /** @description 平台提供的赛事展示名称，未提供时为空。 */
            competition_title?: string | null;
        };
        DimensionInput: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 平台提供的维度中文展示名，原值保存，不由模型翻译或改名。 */
            title: string;
            /** @description 该维度占全部维度总分的比例，由平台提供，四位小数；不是指标内权重。 */
            weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的 AI 渠道比例，由平台显式传入，四位小数。 */
            ai_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的人工渠道比例，与 AI 比例精确相加为1.0000。 */
            human_weight_ratio: components["schemas"]["Ratio"];
        };
        IndicatorDraftInput: {
            /** @description 已有指标原样传回；新增手工指标为空或省略，由服务端分配并回显 */
            indicator_key?: components["schemas"]["ScoringKey"] | null;
            /** @description 本指标的可读名称，随方案草稿编辑并定稿。 */
            title: string | null;
            /** @description 该指标占所属维度的比例，定稿时同维指标比例精确合计1.0000。 */
            weight_ratio: components["schemas"]["Ratio"] | null;
            /** @description 本指标评价的质量及完成程度；草稿可未填，定稿须完整。 */
            evaluation_focus: string | null;
            /** @description 判断所需材料、观察依据及取证方法，不要求当前无法取得的计量。 */
            evidence_requirements: string | null;
            /** @description 连续评分尺度、优劣表现及缺陷影响说明，不是检查项通过率。 */
            scoring_guidance: string | null;
        };
        IndicatorDraft: components["schemas"]["IndicatorDraftInput"] & {
            /** @description 所属维度内的稳定指标键，不使用名称或数组下标替代。 */
            indicator_key: components["schemas"]["ScoringKey"];
        };
        DraftDimensionInput: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 平台确认的维度中文展示名，与稳定维度键分别保存。 */
            title: string;
            /** @description 该维度占全部维度总分的比例，由平台提供，四位小数；不是指标内权重。 */
            weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的 AI 渠道比例，由平台显式传入，四位小数。 */
            ai_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的人工渠道比例，与 AI 比例精确相加为1.0000。 */
            human_weight_ratio: components["schemas"]["Ratio"];
            /** @description 所属维度内按方案顺序保存的指标数组，数量可变。 */
            indicators: components["schemas"]["IndicatorDraftInput"][];
        };
        PlanDimension: components["schemas"]["DraftDimensionInput"] & {
            /** @description 所属维度内按方案顺序保存的指标数组，数量可变。 */
            indicators?: components["schemas"]["IndicatorDraft"][];
        };
        /** @description pass_score > conditional_pass_score；按最终公开舍入分判定。未提供则只出分，不生成通过结论。 */
        DecisionThresholds: {
            /** @description 通过下限，必须高于 conditional_pass_score。 */
            pass_score: components["schemas"]["Score"];
            /** @description 有条件通过下限，必须低于 pass_score。 */
            conditional_pass_score: components["schemas"]["Score"];
        };
        CreatePlanRequest: {
            /** @description 该方案的赛题与要求，不随被测作品表现改变。 */
            challenge: components["schemas"]["Challenge"];
            /** @description 省略时使用赛题名称作为方案名称 */
            title?: string;
            /** @description 平台提供的完整有序 N 维配置；每维五字段，不要求先提供指标，不固定维度数量。 */
            dimensions: components["schemas"]["DimensionInput"][];
            /** @description 平台显式提供的结论阈值；为空或省略时不生成通过结论。 */
            decision_thresholds?: components["schemas"]["DecisionThresholds"] | null;
        };
        SavePlanDraftRequest: {
            /** @description 本次保存的评审方案名称，不能全为空白。 */
            title: string;
            /** @description 该方案的赛题与要求，不随被测作品表现改变。 */
            challenge: components["schemas"]["Challenge"];
            /** @description 本次完整替换的有序维度配置及下属指标草稿；维度比例须合法，指标允许未写完。 */
            dimensions: components["schemas"]["DraftDimensionInput"][];
            /** @description 本次保存的结论阈值，字段必填但可为 null；null 表示不生成通过结论。 */
            decision_thresholds: components["schemas"]["DecisionThresholds"] | null;
        };
        ValidationIssue: {
            /** @description 该对象的稳定机器码，不解析中文消息代替此字段。 */
            code: string;
            /** @description 存在问题的实际字段路径；非单一字段问题为空，不含秘密值。 */
            field: string | null;
            /** @description 给调用方的具体问题说明，不作为机器判定依据。 */
            message: string;
        };
        Plan: {
            /** @description 本租户已创建的评审方案标识，必填且非空。 */
            plan_id: components["schemas"]["Identifier"];
            /** @description 所属资源的业务修订号；跨对象引用必须明确修订属于何种资源。 */
            revision: components["schemas"]["Revision"];
            /** @description 当前修订每次保存/生成提交均递增，不能当成定稿 revision */
            draft_version: components["schemas"]["Revision"];
            /**
             * @description draft 为草稿，finalized 为不可变定稿，生成作业成功不等于定稿。
             * @enum {string}
             */
            status: "draft" | "finalized";
            /** @description 所读修订保存的评审方案名称。 */
            title: string;
            /** @description 该方案的赛题与要求，不随被测作品表现改变。 */
            challenge: components["schemas"]["Challenge"];
            /** @description 按平台保存顺序返回的维度列表，数量、键、名称和比例来自同一规则。 */
            dimensions: components["schemas"]["PlanDimension"][];
            /** @description 平台显式提供的结论阈值；为空或省略时不生成通过结论。 */
            decision_thresholds: components["schemas"]["DecisionThresholds"] | null;
            /** @description 定稿内容 SHA-256 小写十六进制摘要；草稿中为空。 */
            content_sha256: components["schemas"]["Sha256"] | null;
            /** @description 当前或最近方案生成作业；没有时为空，执行状态通过 Job 查询。 */
            generation_job_id: components["schemas"]["NullableId"];
            /** @description 当前草稿内容齐备且无活动生成任务，不代表已定稿或具有定稿权限。 */
            can_finalize: boolean;
            /** @description 草稿中仍需完成的位置和原因；合法保存仍可存在这些问题。 */
            validation_issues: components["schemas"]["ValidationIssue"][];
            /** @description 资源首次成功保存的服务端时间。 */
            created_at: components["schemas"]["Timestamp"];
            /** @description 资源最近成功变更的时间，GET 不修改。 */
            updated_at: components["schemas"]["Timestamp"];
        } & unknown;
        PlanPage: {
            /** @description 授权过滤后的本页方案列表，按 updated_at、plan_id 降序排列。 */
            items: components["schemas"]["PlanListItem"][];
            /** @description 权限与过滤条件相同的总记录数，不含不可见数据。 */
            total: number;
            /** @description 实际返回页码，从1开始，超末页时返回最后有效页。 */
            page: number;
            /** @description 每页最大条目数，默认20、最大100，不是总数。 */
            page_size: number;
        };
        PlanListItem: {
            /** @description 本租户已创建的评审方案标识，必填且非空。 */
            plan_id: components["schemas"]["Identifier"];
            /** @description 所属资源的业务修订号；跨对象引用必须明确修订属于何种资源。 */
            revision: components["schemas"]["Revision"];
            /** @description 该列表项所指方案修订的名称。 */
            title: string;
            /**
             * @description draft 为草稿，finalized 为不可变定稿，生成作业成功不等于定稿。
             * @enum {string}
             */
            status: "draft" | "finalized";
            /** @description 当前或最近方案生成作业；没有时为空，执行状态通过 Job 查询。 */
            generation_job_id: components["schemas"]["NullableId"];
            /** @description 资源最近成功变更的时间，GET 不修改。 */
            updated_at: components["schemas"]["Timestamp"];
        };
        PlanReference: {
            /** @description 本 Run 所引用的评审方案标识，非空。 */
            plan_id: components["schemas"]["Identifier"];
            /** @description 该 PlanReference 所指的不可变定稿方案修订号。 */
            revision: components["schemas"]["Revision"];
            /** @description 该方案定稿修订的内容 SHA-256 摘要，非空。 */
            content_sha256: components["schemas"]["Sha256"];
        };
        CreateReviewRequest: {
            /** @description 本租户已定稿的评审方案标识，创建请求必填且非空。 */
            plan_id: components["schemas"]["Identifier"];
            /** @description 必填的定稿方案修订号，必须与 plan_id 和 content_sha256 指向同一内容；不是 Run 或报告修订。 */
            plan_revision: components["schemas"]["Revision"];
            /** @description 必填的方案定稿内容 SHA-256 小写十六进制摘要，对应 plan_id 和 plan_revision。 */
            content_sha256: components["schemas"]["Sha256"];
            /** @description 平台传入的作品提交/版本标识，原样关联，不由沙箱标识推断。 */
            submission_id: components["schemas"]["Identifier"];
            /** @description 可选作品展示名，省略时使用 submission_id，不由模型猜测作品名称。 */
            title?: string;
            /** @description 平台授权访问的作品入口 URL，实际访问受出网策略约束。 */
            base_url: components["schemas"]["HttpUrl"];
            /** @description 平台源码包下载 URL，与 artifact_id 二选一；签名参数不得进普通日志。 */
            payload_url?: components["schemas"]["HttpUrl"];
            /** @description 已授权的正式产物标识，不是 S3 键或访问凭据。 */
            artifact_id?: components["schemas"]["Identifier"];
            /** @description 平台有限关联信息，不参与计分，不携带秘密或工具权限。 */
            metadata?: components["schemas"]["Metadata"];
        } & (unknown | unknown);
        PreviewCandidate: {
            /** @description 本租户的评审方案标识；尚无所属方案时为空。 */
            plan_id?: components["schemas"]["NullableId"];
            /** @description 预览所选定稿方案的修订号，未选定时可为空；不是 Run 或报告修订。 */
            plan_revision?: components["schemas"]["NullableRevision"];
            /** @description 定稿内容 SHA-256 小写十六进制摘要；草稿中为空。 */
            content_sha256?: components["schemas"]["Sha256"] | null;
            /** @description 平台传入的作品提交/版本标识，原样关联，不由沙箱标识推断。 */
            submission_id?: components["schemas"]["NullableId"];
            /** @description 候选作品展示名，可省略或为空；不改变作品提交标识。 */
            title?: string | null;
            /** @description 平台授权访问的作品入口 URL，实际访问受出网策略约束。 */
            base_url?: components["schemas"]["HttpUrl"] | null;
            /** @description 平台源码包下载 URL，与 artifact_id 二选一；签名参数不得进普通日志。 */
            payload_url?: components["schemas"]["HttpUrl"] | null;
            /** @description 已授权的正式产物标识，不是 S3 键或访问凭据。 */
            artifact_id?: components["schemas"]["NullableId"];
            /** @description 平台有限关联信息，不参与计分，不携带秘密或工具权限。 */
            metadata?: components["schemas"]["Metadata"];
        };
        PreviewRequest: {
            /** @description 自然语言评测要求，仅生成配置候选，不是执行授权。 */
            instruction: string;
            /** @description 平台或用户已选择的可信配置，模型不得覆盖，未补齐字段允许空缺。 */
            context?: components["schemas"]["PreviewCandidate"];
        };
        PreviewResult: {
            /** @description 使用正式创建字段的配置候选；未补齐值不构成有效创建请求。 */
            candidate: components["schemas"]["PreviewCandidate"];
            /** @description 尚缺的创建字段路径；源码二选一缺失另在 issues 说明。 */
            missing_fields: string[];
            /** @description 可修正的配置冲突或缺项，有阻断项时 can_create 必须为 false。 */
            issues: components["schemas"]["ValidationIssue"][];
            /** @description 候选通过当前检查；正式创建时仍检查授权及冻结引用，不代表已接纳。 */
            can_create: boolean;
        };
        /** @enum {string} */
        RunState: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "not_required";
        /** @enum {string|null} */
        Stage: "import" | "collect" | "judge" | "aggregate" | null;
        /** @enum {string} */
        ScoreStatus: "pending" | "partial" | "complete" | "unavailable" | "not_required";
        /** @enum {string} */
        CommentaryStatus: "pending" | "running" | "ready" | "failed" | "not_required";
        /** @enum {string} */
        PublicationStatus: "pending" | "rendering" | "published" | "failed" | "not_required";
        /** @enum {string} */
        ReportType: "ai" | "summary";
        /** @enum {string|null} */
        Decision: "pass" | "conditional_pass" | "fail" | null;
        JobReceipt: {
            /** @description 已持久化后台作业的标识，必填且非空。 */
            job_id: components["schemas"]["Identifier"];
            /**
             * @description 此后台作业的生命周期，succeeded 不表示方案已定稿或整个 Run 已完成。
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** @description 已接纳资源状态的授权相对查询地址。 */
            status_url: components["schemas"]["RelativeUrl"];
        };
        PlanJobReceipt: {
            /** @description 本租户已创建的评审方案标识，必填且非空。 */
            plan_id: components["schemas"]["Identifier"];
            /** @description 所属资源的业务修订号；跨对象引用必须明确修订属于何种资源。 */
            revision: components["schemas"]["Revision"];
            /** @description 同一方案修订内每次草稿保存/生成提交递增的版本，不是定稿编号。 */
            draft_version: components["schemas"]["Revision"];
            /** @description 已持久化后台作业的标识，必填且非空。 */
            job_id: components["schemas"]["Identifier"];
            /**
             * @description 此后台作业的生命周期，succeeded 不表示方案已定稿或整个 Run 已完成。
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** @description 已接纳资源状态的授权相对查询地址。 */
            status_url: components["schemas"]["RelativeUrl"];
        };
        ReviewReceipt: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 平台传入的作品提交/版本标识，原样关联，不由沙箱标识推断。 */
            submission_id: components["schemas"]["Identifier"];
            /** @description 本 Run 绑定的不可变方案修订与摘要，不跟随最新草稿变化。 */
            plan: components["schemas"]["PlanReference"];
            /** @description 所在 Run 或 Job 的执行生命周期，不是评分完整性或比赛结论。 */
            state: components["schemas"]["RunState"];
            /** @description 持久化后台作业标识；没有相应工作时为空。 */
            job_id: components["schemas"]["NullableId"];
            /** @description 资源首次成功保存的服务端时间。 */
            created_at: components["schemas"]["Timestamp"];
            /** @description 已接纳资源状态的授权相对查询地址。 */
            status_url: components["schemas"]["RelativeUrl"];
        };
        RetryRequest: {
            /**
             * @description 恢复对象：未完成评测、公开文案、两路汇总或指定类型报告发布。
             * @enum {string}
             */
            target: "evaluation" | "commentary" | "summary" | "publication";
            /** @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。 */
            report_type?: components["schemas"]["ReportType"];
        } & ({
            /**
             * @description 恢复对象：未完成评测、公开文案、两路汇总或指定类型报告发布。
             * @constant
             */
            target?: "publication";
        } | {
            /**
             * @description 恢复对象：未完成评测、公开文案、两路汇总或指定类型报告发布。
             * @enum {unknown}
             */
            target?: "evaluation" | "commentary" | "summary";
        });
        RetryReceipt: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /**
             * @description 恢复对象：未完成评测、公开文案、两路汇总或指定类型报告发布。
             * @enum {string}
             */
            target: "evaluation" | "commentary" | "summary" | "publication";
            /**
             * @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。
             * @enum {string|null}
             */
            report_type: "ai" | "summary" | null;
            /** @description 接纳时绑定的来源组合；尚无对应结果的修订为 null，不能用一个含义不明的修订号代表两路输入 */
            source: components["schemas"]["ReportSource"];
            /** @description 本次恢复实际执行范围，不表示重跑整次评测。 */
            stages: ("import" | "collect" | "judge" | "aggregate" | "commentary" | "summary" | "render")[];
            /** @description 本操作创建或复用的作业回执，接纳不等于完成。 */
            job: components["schemas"]["JobReceipt"];
        };
        ReviewStatus: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 平台传入的作品提交/版本标识，原样关联，不由沙箱标识推断。 */
            submission_id: components["schemas"]["Identifier"];
            /** @description 接纳时保存的作品展示名，与 submission_id 分开。 */
            title: string;
            /** @description 本 Run 绑定的不可变方案修订与摘要，不跟随最新草稿变化。 */
            plan: components["schemas"]["PlanReference"];
            /** @description 所在 Run 或 Job 的执行生命周期，不是评分完整性或比赛结论。 */
            state: components["schemas"]["RunState"];
            /** @description 自动评测的当前阶段；排队、终态或不需执行时为空。 */
            current_stage: components["schemas"]["Stage"];
            /** @description 取消意图已保存但自动执行尚未确认停止，不另创生命周期。 */
            cancelling: boolean;
            /** @description 该对象必需 AI 评分的齐备情况，partial 保留已有单项。 */
            score_status: components["schemas"]["ScoreStatus"];
            /** @description 所采用 AI 分对应公开文案的状态，不决定分数是否有效。 */
            commentary_status: components["schemas"]["CommentaryStatus"];
            /** @description 当前目标的发布状态，可同时保留以前的可读产物。 */
            publication_status: components["schemas"]["PublicationStatus"];
            /** @description AI 评分快照修订，包含有效分、未完成状态及原因；尚未保存任何快照或无需 AI 时为 null，非空不代表已有有效分。 */
            score_revision: components["schemas"]["NullableRevision"];
            /** @description 与选定 AI 评分对应的公开文案修订，尚无文案时为空。 */
            commentary_revision: components["schemas"]["NullableRevision"];
            /** @description 持久化后台作业标识；没有相应工作时为空。 */
            job_id: components["schemas"]["NullableId"];
            /** @description 本 Run 已导入并登记 ready 的源码包；尚未导入或无需导入时为空。 */
            source_artifact_id: components["schemas"]["NullableId"];
            /**
             * @description 当前等待的资源或依赖，没有等待时为空，不直接表示失败。
             * @enum {string|null}
             */
            wait_reason: "queue" | "model" | "browser" | "source" | "storage" | "dependency" | null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["TaskError"] | null;
            /** @description 当前允许有权调用方恢复的具体目标，不包括已完成或正常等待输入的工作。 */
            recoverable_targets: components["schemas"]["RetryRequest"][];
            /** @description 与状态一致的签名事件位置，用于续读，不是权限凭据。 */
            event_cursor: string;
            /** @description 状态快照对应的 Run 事件水位，十进制字符串，初始为0。 */
            event_sequence: string;
            /** @description 资源首次成功保存的服务端时间。 */
            created_at: components["schemas"]["Timestamp"];
            /** @description 资源最近成功变更的时间，GET 不修改。 */
            updated_at: components["schemas"]["Timestamp"];
        };
        ReviewPage: {
            /** @description 授权过滤后的本页评测列表，按 updated_at、run_id 降序排列。 */
            items: components["schemas"]["ReviewStatus"][];
            /** @description 权限与过滤条件相同的总记录数，不含不可见数据。 */
            total: number;
            /** @description 实际返回页码，从1开始，超末页时返回最后有效页。 */
            page: number;
            /** @description 每页最大条目数，默认20、最大100，不是总数。 */
            page_size: number;
        };
        BatchItemError: {
            /** @description HTTP 错误状态码，不是 Run 状态。 */
            status: number;
            /** @description 该对象的稳定机器码，不解析中文消息代替此字段。 */
            code: string;
            /** @description 脱敏的人类可读原因，不含内部堆栈、秘密或未授权内容。 */
            detail: string;
            /** @description 是否可能在预算与恢复边界内重试，不授权盲目重放副作用。 */
            retryable: boolean;
        };
        BatchCreateItem: {
            /** @description 平台传入的作品提交/版本标识，原样关联，不由沙箱标识推断。 */
            submission_id: components["schemas"]["Identifier"];
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review: components["schemas"]["ReviewReceipt"] | null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["BatchItemError"] | null;
        } & ({
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review?: components["schemas"]["ReviewReceipt"];
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error?: null;
        } | {
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review?: null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error?: components["schemas"]["BatchItemError"];
        });
        BatchCreateResponse: {
            /** @description 按本批请求顺序返回的接纳回执或单项业务错误，不分页。 */
            items: components["schemas"]["BatchCreateItem"][];
            /** @description 本批已持久化接纳数，不是评测完成数。 */
            accepted_count: number;
            /** @description 本批业务拒绝数，不包含被伪装成业务拒绝的基础设施错误。 */
            rejected_count: number;
        };
        BatchStatusItem: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review: components["schemas"]["ReviewStatus"] | null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["BatchItemError"] | null;
        } & ({
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review?: components["schemas"]["ReviewStatus"];
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error?: null;
        } | {
            /** @description 批量条目的单条接纳回执或状态；拒绝时为空且 error 非空。 */
            review?: null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error?: components["schemas"]["BatchItemError"];
        });
        BatchStatusResponse: {
            /** @description 与请求 run_ids 顺序一致的状态或单项不存在错误，不分页。 */
            items: components["schemas"]["BatchStatusItem"][];
            /** @description 本批存在且可见的 Run 数量。 */
            found_count: number;
            /** @description 本批不存在或不可见的 Run 数量，不披露其他租户。 */
            missing_count: number;
        };
        MissingScore: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 所属维度内的稳定指标键，不使用名称或数组下标替代。 */
            indicator_key: components["schemas"]["ScoringKey"] | null;
            /**
             * @description 所缺的评分渠道 ai 或 human，不是报告类型。
             * @enum {string}
             */
            channel: "ai" | "human";
            /**
             * @description 缺项或错误归因，由实际证据确定，不根据超时直接归责选手。
             * @enum {string}
             */
            category: "pending" | "input" | "contestant" | "service" | "provider" | "budget" | "cancelled";
            /** @description 必需评分尚未形成的稳定原因，字段必填且非空；有效分或未要求的项不进入 MissingScore 列表。 */
            reason_code: string;
        };
        IndicatorScore: {
            /** @description 所属维度内的稳定指标键，不使用名称或数组下标替代。 */
            indicator_key: components["schemas"]["ScoringKey"];
            /** @description 冻结方案中该指标的名称。 */
            title: string;
            /** @description 该指标占所属维度的比例，定稿时同维指标比例精确合计1.0000。 */
            weight_ratio: components["schemas"]["Ratio"];
            /**
             * @description scored 为已存有效数值，其他状态分数为空，必要依据与公开文案分开。
             * @enum {string}
             */
            status: "pending" | "scored" | "unavailable" | "not_required";
            /** @description 本指标的0..100连续分；0有效，null 表示尚无有效分。 */
            score: components["schemas"]["NullableScore"];
            /** @description 该指标的已保存 AI 公开评价；文案未形成时为空，展示可回退到已保存 rationale。 */
            comment: components["schemas"]["Comment"];
            /** @description 有效判定的简明事实依据，不是隐藏推理或公开润色。 */
            rationale: components["schemas"]["Comment"];
            /** @description 未形成有效判定的稳定原因；有效分或不需原因时为空。 */
            reason_code: string | null;
            /** @description 该指标判断所采用的 ready 证据产物标识，绑定本评分快照；无已采用证据时为空，不含对象键或访问凭据。读取正文仍需独立证据权限。 */
            evidence_refs: components["schemas"]["Identifier"][];
        } & unknown;
        DimensionScore: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 冻结方案中该维度的中文展示名。 */
            title: string;
            /** @description 该维度占全部维度总分的比例，由平台提供，四位小数；不是指标内权重。 */
            weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的 AI 渠道比例，由平台显式传入，四位小数。 */
            ai_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的人工渠道比例，与 AI 比例精确相加为1.0000。 */
            human_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该对象必需 AI 评分的齐备情况，partial 保留已有单项。 */
            score_status: components["schemas"]["ScoreStatus"];
            /** @description 该对象按冻结规则计算的 AI 分；必需项未齐或不要求时为空。 */
            ai_score: components["schemas"]["NullableScore"];
            /** @description 所属对象的公开评价，人工原文保持，自动文案失败可为空。 */
            comment: components["schemas"]["Comment"];
            /** @description 所属维度内按方案顺序保存的指标数组，数量可变。 */
            indicators: components["schemas"]["IndicatorScore"][];
        };
        Scores: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 本 Run 绑定的不可变方案修订与摘要，不跟随最新草稿变化。 */
            plan: components["schemas"]["PlanReference"];
            /** @description AI 评分快照修订，包含有效分、未完成状态及原因；尚未保存任何快照或无需 AI 时为 null，非空不代表已有有效分。 */
            score_revision: components["schemas"]["NullableRevision"];
            /** @description 该对象必需 AI 评分的齐备情况，partial 保留已有单项。 */
            score_status: components["schemas"]["ScoreStatus"];
            /** @description 与选定 AI 评分对应的公开文案修订，尚无文案时为空。 */
            commentary_revision: components["schemas"]["NullableRevision"];
            /** @description 所采用 AI 分对应公开文案的状态，不决定分数是否有效。 */
            commentary_status: components["schemas"]["CommentaryStatus"];
            /** @description 按 PRD 中全部必需 AI 渠道系数计算的 AI 总分，不是两路混合总分；缺必需项为空。 */
            ai_score: components["schemas"]["NullableScore"];
            /** @description 完整公开分按显式阈值得到的结论，无阈值或无完整分则为空。 */
            decision: components["schemas"]["Decision"];
            /** @description 总体评价，在人工对象中为平台原文，在 AI 对象中为已存自动评价。 */
            overall_comment: components["schemas"]["Comment"];
            /** @description 仅基于已保存事实的少量建议，不新增评分或虚构问题。 */
            recommendations: string[];
            /** @description 按平台保存顺序返回的维度列表，数量、键、名称和比例来自同一规则。 */
            dimensions: components["schemas"]["DimensionScore"][];
            /** @description 规则确实要求但尚缺的评分，不含零权重或未要求渠道。 */
            missing_scores: components["schemas"]["MissingScore"][];
        };
        HumanDimensionInput: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 本次完整提交的有效人工分，必填且不能为 null；0 是真实有效分。 */
            human_score: components["schemas"]["Score"];
            /** @description 该维度人工原始评语，省略或 null 保存为空，不继承上一版。 */
            comment?: components["schemas"]["Comment"];
        };
        HumanResultsRequest: {
            /** @description 调用方所见人工修订，首次为0；提交时比较以防旧结果覆盖新结果。 */
            expected_revision: number;
            /** @description 本次完整提交的人工结果；必须覆盖 W×h>0 的维度，可附 W=0 且 h>0 的维度，不含 AI 分或权重。 */
            dimensions: components["schemas"]["HumanDimensionInput"][];
            /** @description 平台提交的人工总体原文；省略或 null 保存为空，不继承上一版。 */
            overall_comment?: components["schemas"]["Comment"];
        };
        HumanResults: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 当前人工结果修订，0表示从未提交，后续从1递增。 */
            revision: number;
            /** @description 已保存人工修订中的结果，按冻结方案维度顺序返回；revision=0 时为空数组。 */
            dimensions: components["schemas"]["HumanDimensionInput"][];
            /** @description 该人工修订保存的总体原文；未提交或未填写时为 null。 */
            overall_comment: components["schemas"]["Comment"];
            /** @description 该人工修订成功持久化的服务端时间，尚无结果时为空。 */
            submitted_at: components["schemas"]["NullableTimestamp"];
        };
        HumanResultsReceipt: {
            /** @description 已经原子保存的人工分和原始评语，不附 AI 分。 */
            human_results: components["schemas"]["HumanResults"];
            /** @description 人工结果保存时同事务登记的汇总更新任务，不要求提交方等待完成。 */
            summary_job: components["schemas"]["JobReceipt"];
        };
        /** @description 汇总快照的完整来源组合。仅文案修订变化时复用已存数值形成新快照，不调用模型或重评。 */
        SourceRevisions: {
            /** @description 所引用不可变定稿方案的业务修订号。 */
            plan_revision: components["schemas"]["Revision"];
            /** @description AI 评分快照修订，包含有效分、未完成状态及原因；尚未保存任何快照或无需 AI 时为 null，非空不代表已有有效分。 */
            score_revision: components["schemas"]["NullableRevision"];
            /** @description 采用的人工结果修订，尚无结果或不适用时为空。 */
            human_revision: components["schemas"]["NullableRevision"];
            /** @description 此汇总快照采用且与 score_revision 匹配的公开文案修订；无已存文案时为 null，不阻塞分数汇总。 */
            commentary_revision: components["schemas"]["NullableRevision"];
        };
        SummaryDimension: {
            /** @description 平台提供的稳定维度英文键，在方案内唯一，不由模型改名。 */
            dimension_key: components["schemas"]["ScoringKey"];
            /** @description 冻结方案中该维度的中文展示名。 */
            title: string;
            /** @description 该维度占全部维度总分的比例，由平台提供，四位小数；不是指标内权重。 */
            weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的 AI 渠道比例，由平台显式传入，四位小数。 */
            ai_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该维度的人工渠道比例，与 AI 比例精确相加为1.0000。 */
            human_weight_ratio: components["schemas"]["Ratio"];
            /** @description 该对象按冻结规则计算的 AI 分；必需项未齐或不要求时为空。 */
            ai_score: components["schemas"]["NullableScore"];
            /** @description 该维度的有效人工分；所需人工结果尚未提交时为空。 */
            human_score: components["schemas"]["NullableScore"];
            /** @description 该维度或全部维度的汇总分；必需两路未齐时为空。 */
            final_score: components["schemas"]["NullableScore"];
            /** @description 已保存的维度 AI 评价，可为空且不改变分数。 */
            ai_comment: components["schemas"]["Comment"];
            /** @description 该汇总采用的维度人工原始评语。 */
            human_comment: components["schemas"]["Comment"];
            /** @description 与 source_revisions.score_revision 对应的全部冻结指标及已有 AI 分，按方案顺序；缺维度分仍保留有效指标分，人工维度原文不复制到每个指标。 */
            indicators: components["schemas"]["IndicatorScore"][];
        };
        Summary: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 本 Run 绑定的不可变方案修订与摘要，不跟随最新草稿变化。 */
            plan: components["schemas"]["PlanReference"];
            /** @description 确定性汇总修订，尚未保存汇总时为空。 */
            summary_revision: components["schemas"]["NullableRevision"];
            /**
             * @description 所保存汇总的必需评分齐备程度，仅 complete 可有总分。
             * @enum {string}
             */
            summary_status: "pending" | "partial" | "complete";
            /** @description 该汇总实际采用的规则、AI 与人工修订。 */
            source_revisions: components["schemas"]["SourceRevisions"];
            /** @description 当前有效输入指针，用于判断已保存汇总是否最新。 */
            current_source_revisions: components["schemas"]["SourceRevisions"];
            /** @description 查询时比较来源与当前目标的结果，不写进不可变正文，也不表示评分已完整。 */
            is_latest: boolean;
            /** @description 当前汇总更新任务，没有时为空。 */
            update_job_id: components["schemas"]["NullableId"];
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["TaskError"] | null;
            /** @description 该维度或全部维度的汇总分；必需两路未齐时为空。 */
            final_score: components["schemas"]["NullableScore"];
            /** @description 完整公开分按显式阈值得到的结论，无阈值或无完整分则为空。 */
            decision: components["schemas"]["Decision"];
            /** @description 本汇总采用的人工总体原文，不经模型改写。 */
            overall_human_comment: components["schemas"]["Comment"];
            /** @description 按平台保存顺序返回的维度列表，数量、键、名称和比例来自同一规则。 */
            dimensions: components["schemas"]["SummaryDimension"][];
            /** @description 规则确实要求但尚缺的评分，不含零权重或未要求渠道。 */
            missing_scores: components["schemas"]["MissingScore"][];
        };
        ReportSource: {
            /** @description 所引用不可变定稿方案的业务修订号。 */
            plan_revision: components["schemas"]["Revision"];
            /** @description AI 评分快照修订，包含有效分、未完成状态及原因；尚未保存任何快照或无需 AI 时为 null，非空不代表已有有效分。 */
            score_revision: components["schemas"]["NullableRevision"];
            /** @description 采用的人工结果修订，尚无结果或不适用时为空。 */
            human_revision: components["schemas"]["NullableRevision"];
            /** @description 确定性汇总修订，尚未保存汇总时为空。 */
            summary_revision: components["schemas"]["NullableRevision"];
            /** @description 与选定 AI 评分对应的公开文案修订，尚无文案时为空。 */
            commentary_revision: components["schemas"]["NullableRevision"];
        };
        PublishedReport: {
            /** @description 同一 Run 同一报告类型的不可变发布修订，不是评分修订。 */
            report_revision: components["schemas"]["Revision"];
            /** @description 本报告绑定的完整来源修订对象，必填且非空；其中不适用的评分、人工、汇总或文案修订成员为 null。 */
            source: components["schemas"]["ReportSource"];
            /** @description 查询时比较来源与当前目标的结果，不写进不可变正文，也不表示评分已完整。 */
            is_latest: boolean;
            /** @description 该发布修订 JSON 正文的授权相对地址。 */
            json_url: components["schemas"]["RelativeUrl"];
            /** @description 与 JSON 同来源修订的 HTML 正文地址。 */
            html_url: components["schemas"]["RelativeUrl"];
            /** @description 本不可变报告修订的生成时间，不随刷新变化。 */
            generated_at: components["schemas"]["Timestamp"];
        };
        Publication: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。 */
            report_type: components["schemas"]["ReportType"];
            /** @description 当前目标的发布状态，可同时保留以前的可读产物。 */
            publication_status: components["schemas"]["PublicationStatus"];
            /** @description 本次目标发布的来源组合，尚无目标时为空。 */
            target_source: components["schemas"]["ReportSource"] | null;
            /** @description 持久化后台作业标识；没有相应工作时为空。 */
            job_id: components["schemas"]["NullableId"];
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["TaskError"] | null;
            /** @description 最近两种正文均已就绪的报告，可能不是最新目标，首次发布前为空。 */
            published: components["schemas"]["PublishedReport"] | null;
        };
        /** @description 不可变汇总正文，不保存 is_latest、当前指针或后台 Job 等易变查询字段。 */
        SummarySnapshot: {
            /** @description 本 Run 绑定的不可变方案修订与摘要，不跟随最新草稿变化。 */
            plan: components["schemas"]["PlanReference"];
            /** @description 该不可变报告正文引用的已保存汇总修订，必填且非空。 */
            summary_revision: components["schemas"]["Revision"];
            /**
             * @description 所保存汇总的必需评分齐备程度，仅 complete 可有总分。
             * @enum {string}
             */
            summary_status: "pending" | "partial" | "complete";
            /** @description 该汇总实际采用的规则、AI 与人工修订。 */
            source_revisions: components["schemas"]["SourceRevisions"];
            /** @description 该维度或全部维度的汇总分；必需两路未齐时为空。 */
            final_score: components["schemas"]["NullableScore"];
            /** @description 完整公开分按显式阈值得到的结论，无阈值或无完整分则为空。 */
            decision: components["schemas"]["Decision"];
            /** @description 本汇总采用的人工总体原文，不经模型改写。 */
            overall_human_comment: components["schemas"]["Comment"];
            /** @description 按平台保存顺序返回的维度列表，数量、键、名称和比例来自同一规则。 */
            dimensions: components["schemas"]["SummaryDimension"][];
            /** @description 规则确实要求但尚缺的评分，不含零权重或未要求渠道。 */
            missing_scores: components["schemas"]["MissingScore"][];
        };
        ReportDocument: {
            /**
             * @description 本消息或正文的格式版本，区别于模型、方案修订和工具协议版本。
             * @constant
             */
            schema_version: "1.0";
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 从已保存作品名称形成的报告标题，不由渲染阶段重新命名作品。 */
            title: string;
            /** @description 平台提供的赛事展示名称，未提供时为空。 */
            competition_title: string | null;
            /** @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。 */
            report_type: components["schemas"]["ReportType"];
            /** @description 同一 Run 同一报告类型的不可变发布修订，不是评分修订。 */
            report_revision: components["schemas"]["Revision"];
            /** @description 本报告绑定的完整来源修订对象，必填且非空；其中不适用的评分、人工、汇总或文案修订成员为 null。 */
            source: components["schemas"]["ReportSource"];
            /** @description 本不可变报告修订的生成时间，不随刷新变化。 */
            generated_at: components["schemas"]["Timestamp"];
            /** @description 独立 AI 报告的评分快照，在汇总报告中为空。 */
            ai_result: components["schemas"]["Scores"] | null;
            /** @description 汇总报告的不可变数据，在 AI 报告中为空。 */
            summary_result: components["schemas"]["SummarySnapshot"] | null;
            /** @description 该报告生成时的脱敏诊断，不替代已有评分。 */
            diagnostics: components["schemas"]["TaskError"][];
        } & ({
            /**
             * @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。
             * @constant
             */
            report_type?: "ai";
            /** @description 独立 AI 报告的评分快照，在汇总报告中为空。 */
            ai_result?: components["schemas"]["Scores"];
            /** @description 汇总报告的不可变数据，在 AI 报告中为空。 */
            summary_result?: null;
        } | {
            /**
             * @description 报告类别：ai 为独立 AI 报告，summary 为两路汇总报告。
             * @constant
             */
            report_type?: "summary";
            /** @description 独立 AI 报告的评分快照，在汇总报告中为空。 */
            ai_result?: null;
            /** @description 汇总报告的不可变数据，在 AI 报告中为空。 */
            summary_result?: components["schemas"]["SummarySnapshot"];
        });
        /** @enum {string} */
        EvidenceKind: "screenshot" | "dom" | "source_excerpt" | "source_archive" | "code_analysis" | "interaction" | "runtime_error";
        EvidenceItem: {
            /** @description 已授权的正式产物标识，不是 S3 键或访问凭据。 */
            artifact_id: components["schemas"]["Identifier"];
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 该对象的类型，按其枚举解释，不从摘要推断。 */
            kind: components["schemas"]["EvidenceKind"];
            /** @description 证据列表的脱敏可读标题，不是原始存储路径。 */
            title: string;
            /** @description 核对后的产物媒体类型，不仅依据文件扩展名。 */
            media_type: string;
            /** @description 产物实际大小，以 bytes 计。 */
            size_bytes: number;
            /** @description 实际产物内容摘要，不替代权限和归属校验。 */
            sha256: components["schemas"]["Sha256"];
            /** @description 仅作品归档内相对路径；不提供宿主绝对路径 */
            source_path: string | null;
            /** @description 此产物正文的授权读取地址，标识本身不授予访问权。 */
            content_url: components["schemas"]["RelativeUrl"];
            /** @description 资源首次成功保存的服务端时间。 */
            created_at: components["schemas"]["Timestamp"];
        };
        EvidencePage: {
            /** @description 授权过滤后的本页证据，按 created_at、artifact_id 降序排列。 */
            items: components["schemas"]["EvidenceItem"][];
            /** @description 权限与过滤条件相同的总记录数，不含不可见数据。 */
            total: number;
            /** @description 实际返回页码，从1开始，超末页时返回最后有效页。 */
            page: number;
            /** @description 每页最大条目数，默认20、最大100，不是总数。 */
            page_size: number;
        };
        TaskError: {
            /** @description 该对象的稳定机器码，不解析中文消息代替此字段。 */
            code: string;
            /**
             * @description 事件或错误所属阶段，不适用时为空，不是执行生命周期。
             * @enum {string|null}
             */
            stage: "planner" | "preview" | "import" | "collect" | "judge" | "aggregate" | "human_results" | "summary" | "commentary" | "render" | null;
            /**
             * @description 缺项或错误归因，由实际证据确定，不根据超时直接归责选手。
             * @enum {string}
             */
            category: "input" | "contestant" | "service" | "provider" | "budget" | "cancelled";
            /** @description 是否可能在预算与恢复边界内重试，不授权盲目重放副作用。 */
            retryable: boolean;
            /** @description 脱敏的人类可读原因，不含内部堆栈、秘密或未授权内容。 */
            detail: string;
            /** @description 此协议请求的关联标识；HTTP、工具传输分别有独立作用域。 */
            request_id: string | null;
        };
        Problem: {
            /**
             * Format: uri-reference
             * @description Problem Details 类型 URI，不是内部异常类名。
             */
            type: string;
            /** @description 此 HTTP 错误类别的简短标题，不是机器码。 */
            title: string;
            /** @description HTTP 错误状态码，不是 Run 状态。 */
            status: number;
            /** @description 该对象的稳定机器码，不解析中文消息代替此字段。 */
            code: string;
            /** @description 脱敏的人类可读原因，不含内部堆栈、秘密或未授权内容。 */
            detail: string;
            /**
             * Format: uri-reference
             * @description 发生 HTTP 错误的请求路径，不含敏感查询参数。
             */
            instance: string;
            /** @description 此协议请求的关联标识；HTTP、工具传输分别有独立作用域。 */
            request_id: string;
            /** @description 是否可能在预算与恢复边界内重试，不授权盲目重放副作用。 */
            retryable: boolean;
            /** @description 字段级问题数组，非字段错误为空数组。 */
            errors: components["schemas"]["ValidationIssue"][];
        };
        Job: {
            /** @description 已持久化后台作业的标识，必填且非空。 */
            job_id: components["schemas"]["Identifier"];
            /**
             * @description 该对象的类型，按其枚举解释，不从摘要推断。
             * @enum {string}
             */
            kind: "planner" | "preview" | "evaluation" | "commentary" | "summary" | "render";
            /**
             * @description 此后台作业的生命周期，succeeded 不表示方案已定稿或整个 Run 已完成。
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** @description 本租户的评审方案标识；尚无所属方案时为空。 */
            plan_id: components["schemas"]["NullableId"];
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["NullableId"];
            /** @description 成功作业的类型化输出或资源引用；未成功时为空，不泄露受限正文。 */
            result: components["schemas"]["PreviewResult"] | components["schemas"]["JobOutputReference"] | null;
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["TaskError"] | null;
            /** @description 资源首次成功保存的服务端时间。 */
            created_at: components["schemas"]["Timestamp"];
            /** @description 资源最近成功变更的时间，GET 不修改。 */
            updated_at: components["schemas"]["Timestamp"];
        };
        /** @description 仅引用，不在 Job 查询泄露无权读取的评分正文 */
        JobOutputReference: {
            /** @description 作业产出引用，后续读取仍需对象权限。 */
            resource_url: components["schemas"]["RelativeUrl"];
            /** @description resource_url 所指资源的业务修订；没有该类修订时为 null。资源类型由受控路径明确，不独立传递裸修订号。 */
            revision: components["schemas"]["NullableRevision"];
        };
        RuntimeEvent: {
            /**
             * @description 本消息或正文的格式版本，区别于模型、方案修订和工具协议版本。
             * @constant
             */
            schema_version: "1";
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description Run 内严格递增的十进制字符串序号，不要求相邻连续。 */
            sequence: string;
            /**
             * @description 该对象的类型，按其枚举解释，不从摘要推断。
             * @enum {string}
             */
            kind: "run.state_changed" | "stage.started" | "tool.started" | "tool.completed" | "tool.failed" | "evidence.ready" | "score.saved" | "human_result.saved" | "summary.changed" | "commentary.changed" | "publication.changed";
            /** @description 持久化执行事件的发生时间。 */
            occurred_at: components["schemas"]["Timestamp"];
            /** @description 事件或错误所属阶段，不适用时为空，不是执行生命周期。 */
            stage: components["schemas"]["Stage"];
            /** @description 事件短摘要，不是两路计分汇总或模型隐藏推理。 */
            summary: string;
            /** @description 按 kind 确定的类型化事件内容，不接受任意原始模型输出。 */
            data: Record<string, never>;
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        ToolEventData: {
            /** @description Runtime 工具执行调用标识，不等于模型供应商请求或 HTTP 请求。 */
            call_id: components["schemas"]["Identifier"];
            /** @description 受控注册的工具规范名，不是任意命令。 */
            tool_name: string;
            /** @description 调用耗时，以毫秒计；尚未完成时为空，不以0冒充未知。 */
            duration_ms: number | null;
            /** @description 已保存并登记 ready 的正式产物引用。 */
            artifact_ids: components["schemas"]["Identifier"][];
            /** @description 当前失败步骤的脱敏错误；无错误时为空，不等于查询请求失败。 */
            error: components["schemas"]["TaskError"] | null;
        };
        EventPage: {
            /** @description 一次作品评测的标识，重测创建新 Run，不是作品提交号或后台 Job。 */
            run_id: components["schemas"]["Identifier"];
            /** @description 可见事件，按 sequence 升序返回；不是普通列表的页码分页。 */
            items: components["schemas"]["RuntimeEvent"][];
            /** @description 续读签名游标，无新事件时也返回有效位置。 */
            next_cursor: string;
            /** @description 当前水位是否仍有未交付事件，不代表后台任务是否结束。 */
            has_more: boolean;
        };
        StreamControl: {
            /** @description 该对象的稳定机器码，不解析中文消息代替此字段。 */
            code: string;
            /**
             * @description 订阅控制动作：重同步、重新授权或重连，不触发重评。
             * @enum {string}
             */
            action: "resync" | "reauthenticate" | "reconnect";
            /** @description 是否可能在预算与恢复边界内重试，不授权盲目重放副作用。 */
            retryable: boolean;
        };
    };
    responses: {
        /** @description 按 README 中的 HTTP/稳定码映射返回；不把异步 Job 失败当作查询请求失败 */
        Problem: {
            headers: {
                "X-Request-ID"?: string;
                /** @description 仅可重试的限流或暂不可用，十进制秒数 */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 已保存的方案值与完整性问题 */
        Plan: {
            headers: {
                /** @description 当前方案内容的强 ETag，提交编辑/定稿时原样回传 */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Plan"];
            };
        };
    };
    parameters: {
        /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
        IdempotencyKey: string;
        /** @description 原样传回当前方案 ETag，不接受 *。先检查幂等原回执，再检查版本。 */
        IfMatch: string;
        PlanId: components["schemas"]["Identifier"];
        RunId: components["schemas"]["Identifier"];
        Page: number;
        PageSize: number;
        Search: string;
        /** @description 不透明独占起点；SSE 重连优先 Last-Event-ID */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPlans: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                q?: components["parameters"]["Search"];
                status?: "draft" | "finalized";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 每方案一条，默认展示当前草稿，否则最新定稿；按 updated_at、plan_id 倒序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description 输入和生成 Job 已持久化，不等于方案定稿 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanJobReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPlan: {
        parameters: {
            query?: {
                /** @description 指定时仅读取不可变定稿；省略时当前草稿优先，否则最新定稿 */
                revision?: components["schemas"]["Revision"];
            };
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Plan"];
            default: components["responses"]["Problem"];
        };
    };
    savePlanDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 原样传回当前方案 ETag，不接受 *。先检查幂等原回执，再检查版本。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlanDraftRequest"];
            };
        };
        responses: {
            200: components["responses"]["Plan"];
            default: components["responses"]["Problem"];
        };
    };
    generateMissingPlanDimensions: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 原样传回当前方案 ETag，不接受 *。先检查幂等原回执，再检查版本。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接纳生成任务 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanJobReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    finalizePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description 原样传回当前方案 ETag，不接受 *。先检查幂等原回执，再检查版本。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Plan"];
            default: components["responses"]["Problem"];
        };
    };
    previewReview: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description 解析 Job 已持久化 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                q?: components["parameters"]["Search"];
                state?: components["schemas"]["RunState"];
                submission_id?: components["schemas"]["Identifier"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按 updated_at、run_id 倒序；状态不含 AI 分与评语正文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Run 与必要 Job 同事务接纳；全人工时 state=not_required、job_id=null */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createReviewsBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 按提交顺序排列的单条评测创建请求，1 至 100 项；字段与单条创建完全相同，不要求 item_key。列表位置参与本批次幂等身份。 */
                    items: components["schemas"]["CreateReviewRequest"][];
                };
            };
        };
        responses: {
            /** @description 按原顺序返回每项回执或业务错误；整批结构错误返回 422，基础设施故障可返回 503，原键重试可恢复已完成回执 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCreateResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReviewStatusesBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 本次查询的评测运行标识，1 至 100 个且不重复；响应保留此顺序，不存在或不可见的 Run 返回单项错误。 */
                    run_ids: components["schemas"]["Identifier"][];
                };
            };
        };
        responses: {
            /** @description 顺序与 run_ids 相同，单项不可见或不存在返回 RUN_NOT_FOUND */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatusResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评测失败时查询仍返回 200，以结构化 error 说明原因 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelReview: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 意图及实际 state/cancelling */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    retryReviewPart: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description 创建或复用恢复 Job，回执明确目标和绑定修订 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 未形成分数时返回明确状态、null 分数和全部冻结维度，不返回 409 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scores"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHumanResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 无结果时 revision=0、dimensions=[]、submitted_at=null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanResults"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    submitHumanResults: {
        parameters: {
            query?: never;
            header: {
                /** @description 同租户、同调用来源、同 HTTP 操作及资源路径的稳定请求键；重试使用原键、原内容与原前置版本。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanResultsRequest"];
            };
        };
        responses: {
            /** @description 人工修订和汇总意图已保存，回显本次人工分及原文，不等待 AI 或 HTML */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanResultsReceipt"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已保存来源组合的汇总；更新排队时标记 is_latest=false，不把旧结果当成最新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPublication: {
        parameters: {
            query?: {
                report_type?: components["schemas"]["ReportType"];
            };
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前目标与最近可读发布分别返回；正文/下载固定同一修订 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEvidence: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                kind?: components["schemas"]["EvidenceKind"];
            };
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仅返回 ready 产物元信息和授权相对地址，不内嵌整份源码或图片；稳定按 created_at、artifact_id 倒序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    readArtifactContent: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                artifact_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正文按 media_type 返回。非可信 HTML 源码/DOM 强制 attachment 或 text/plain，报告 HTML 使用可信模板与 CSP。JSON 报告符合 ReportDocument；其他 JSON 证据作为不透明附件下载。 */
            200: {
                headers: {
                    ETag?: string;
                    "Content-Disposition"?: string;
                    "Content-Security-Policy"?: string;
                    "X-Content-Type-Options"?: "nosniff";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDocument"];
                    "text/html": string;
                    "text/plain": string;
                    "image/png": unknown;
                    "image/jpeg": unknown;
                    "image/webp": unknown;
                    "application/octet-stream": unknown;
                };
            };
            /** @description 已授权且 ETag 匹配，没有响应正文，不是失败 */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listReviewEvents: {
        parameters: {
            query?: {
                /** @description 不透明独占起点；SSE 重连优先 Last-Event-ID */
                cursor?: components["parameters"]["Cursor"];
                limit?: number;
            };
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最多 256 KiB；按可见事件过滤，next_cursor 可越过无权读取的事件，不泄露内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamReviewEvents: {
        parameters: {
            query?: {
                /** @description 不透明独占起点；SSE 重连优先 Last-Event-ID */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description review_event 帧的 data 为 RuntimeEvent；id 为签名游标。stream_control 为 StreamControl，无 id。心跳为注释。头发出后不能再修改 HTTP 状态，断开不取消任务。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 失败 Job 也返回 200，失败详情在 error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
